const oracledb = require('oracledb');
const fs = require('fs');
require('dotenv').config();

async function runMigrate() {
    let connection;
    try {
        connection = await oracledb.getConnection({
            user: process.env.DB_USER,
            password: process.env.DB_PASSWORD,
            connectString: process.env.DB_CONNECT_STRING
        });

        console.log("Terhubung ke database, membuat tabel...");

        const ddlStatements = [
            `CREATE TABLE users (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nama VARCHAR2(100) NOT NULL,
                email VARCHAR2(100) NOT NULL UNIQUE,
                password VARCHAR2(255) NOT NULL,
                role VARCHAR2(10) DEFAULT 'user' CHECK (role IN ('user', 'admin')),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )`,
            `CREATE TABLE brands (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nama VARCHAR2(100) NOT NULL UNIQUE,
                logo VARCHAR2(255) NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )`,
            `CREATE TABLE products (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nama VARCHAR2(150) NOT NULL,
                brand VARCHAR2(50) NOT NULL,
                kategori VARCHAR2(50) NOT NULL,
                harga NUMBER(12,2) NOT NULL,
                deskripsi VARCHAR2(4000),
                gambar VARCHAR2(255),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )`,
            `CREATE TABLE product_sizes (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                product_id NUMBER NOT NULL,
                ukuran NUMBER NOT NULL,
                stok NUMBER DEFAULT 0 NOT NULL,
                CONSTRAINT fk_ps_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
            )`,
            `CREATE TABLE cart_items (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id NUMBER NOT NULL,
                product_id NUMBER NOT NULL,
                ukuran NUMBER NOT NULL,
                qty NUMBER DEFAULT 1 NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_ci_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                CONSTRAINT fk_ci_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
            )`,
            `CREATE TABLE orders (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id NUMBER NOT NULL,
                total_harga NUMBER(12,2) NOT NULL,
                status VARCHAR2(20) DEFAULT 'pending' CHECK (status IN ('pending', 'diproses', 'dikirim', 'selesai')),
                alamat_pengiriman VARCHAR2(4000) NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
            )`,
            `CREATE TABLE order_items (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                order_id NUMBER NOT NULL,
                product_id NUMBER NOT NULL,
                ukuran NUMBER NOT NULL,
                qty NUMBER NOT NULL,
                harga_satuan NUMBER(12,2) NOT NULL,
                CONSTRAINT fk_oi_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
                CONSTRAINT fk_oi_product FOREIGN KEY (product_id) REFERENCES products(id)
            )`,
            `CREATE TABLE reviews (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                product_id NUMBER NOT NULL,
                user_id NUMBER NOT NULL,
                rating NUMBER NOT NULL CHECK (rating BETWEEN 1 AND 5),
                komentar VARCHAR2(4000),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_review_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
                CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
            )`
        ];

        for (let sql of ddlStatements) {
            try {
                await connection.execute(sql);
                console.log("Tabel dibuat.");
            } catch (e) {
                if (e.errorNum === 955) {
                    console.log("Tabel sudah ada, mengabaikan...");
                } else {
                    console.error("Error creating table:", e.message);
                }
            }
        }

        console.log("Migrasi selesai!");
    } catch (err) {
        console.error("Koneksi gagal:", err);
    } finally {
        if (connection) {
            await connection.close();
        }
    }
}

runMigrate();
