const oracledb = require('oracledb');
const fs = require('fs');
require('dotenv').config();

async function runMigrate() {
    let connection;
    try {
        connection = await oracledb.getConnection({
            user: process.env.DB_USER,
            password: process.env.DB_PASSWORD,
            connectString: process.env.DB_CONNECT_STRING
        });

        console.log("Terhubung ke database, mengupdate skema...");

        try {
            await connection.execute(`ALTER TABLE users ADD no_hp VARCHAR2(20)`);
            console.log("Kolom no_hp ditambahkan ke users.");
        } catch (e) {
            if (e.errorNum === 1430) {
                console.log("Kolom no_hp sudah ada di users.");
            } else {
                console.error("Error menambah kolom no_hp:", e.message);
            }
        }

        const createAddressTable = `
            CREATE TABLE user_addresses (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id NUMBER NOT NULL,
                label VARCHAR2(50) NOT NULL,
                alamat VARCHAR2(4000) NOT NULL,
                is_default NUMBER(1) DEFAULT 0,
                CONSTRAINT fk_ua_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
            )
        `;

        try {
            await connection.execute(createAddressTable);
            console.log("Tabel user_addresses dibuat.");
        } catch (e) {
            if (e.errorNum === 955) {
                console.log("Tabel user_addresses sudah ada.");
            } else {
                console.error("Error membuat tabel user_addresses:", e.message);
            }
        }

        console.log("Update skema selesai!");
    } catch (err) {
        console.error("Koneksi gagal:", err);
    } finally {
        if (connection) {
            await connection.close();
        }
    }
}

runMigrate();
